services:
  frontend:
    build:
      context: ./agri-oasis-market
      dockerfile: Dockerfile
    image: agri-oasis-frontend:latest
    ports:
      - "3000:80"   # host : container
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: agri-oasis-backend:latest
    ports:
      - "8080:8085"
    environment:
      - MONGODB_URL=${MONGODB_URL}
    restart: unless-stopped
