version: "3.8"

services:
  frontend:
    build:
      context: ./agri-oasis-market
      dockerfile: Dockerfile
    image: agri-oasis-frontend:latest
    ports:
      - "5173:80"   # host : container
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: agri-oasis-backend:latest
    ports:
      - "8085:8085"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    restart: unless-stopped
